django_todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
       "", include("tasks.urls", namespace="tasks")
   ),
]

tasks/urls.py
from django.urls import path

from tasks.views import TaskListView, TaskCreateView, toggle_task_status, TaskUpdateView, TaskDeleteView, TagListView, \
   TagCreateView, TagDeleteView, TagUpdateView

urlpatterns = [
   path("", TaskListView.as_view(), name = "home"),
   path("tasks/create/", TaskCreateView.as_view(), name="task-form"),
   path("tasks/<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
   path("tasks/<int:pk>/delete", TaskDeleteView.as_view(), name="task-delete"),

   path("<int:pk>/toggle/", toggle_task_status, name="task-toggle"),
   path("tags/", TagListView.as_view(), name="tag-list"),
   path("tags/create", TagCreateView.as_view(), name="tag-create"),
   path("tags/<int:pk>/delete", TagDeleteView.as_view(), name="tag-delete"),
   path("tags/<int:pk>/update", TagUpdateView.as_view(), name="tag-update"),

]

app_name="tasks"

tasks/models.py
from django.db import models


class Task(models.Model):
    content = models.TextField()
    created_datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks", blank=True)

    class Meta:
        ordering = ["is_done", "created_datetime"]

    def __str__(self) -> str:
        if len(self.content)>30:
            return f"{self.content[:30]}..."
        else:
            return self.content


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self) -> str:
        return self.name

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["content", "deadline", "tags"]
        widgets = {
            "deadline": forms.DateTimeInput(attrs={"type": "datetime-local"})
        }

tasks/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic, View

from tasks.forms import TaskForm
from tasks.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "tasks/task_list.html"
    paginate_by = 5
    context_object_name = "tasks"

    def get_queryset(self):
        return Task.objects.prefetch_related('tags')


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/task_form.html"
    success_url = reverse_lazy("tasks:home")


def toggle_task_status(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = not task.is_done
    task.save()
    return redirect("tasks:home")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:home")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:home")


class TagListView(generic.ListView):
    model = Tag
    template_name = "tasks/tag_list.html"
    context_object_name = "tags"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    template_name = "tasks/tag_form.html"
    success_url = reverse_lazy("tasks:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <title>Todo list</title>
</head>

<body>
  <div class="container-fluid">
    <div class="row"    >
      <div class="col-2 bg-light p-3">
        {% include "includes/sidebar.html" %}
      </div>
      <main class="col p-4">
        {% block content %}{% endblock %}
          {% block pagination %}
              {% include "includes/pagination.html" %}
            {% endblock %}
      </main>
    </div>
  </div>

</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'tasks:home' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:tag-list' %}">Tags</a>
</ul>

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task</h1>
  <p>Are you sure?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'tasks:tag-list' %}" class="btn btn-secondary">No</a>

  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h2>{{ object|yesno:"Update,Create" }} tag</h2>
 <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Add tag" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}
<h1>Tag List <a href="{% url 'tasks:tag-create' %}" class="btn btn-primary float-end">Add Tag</a></h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for tag in tags %}
        <tr>
            <td>{{ tag.name }}</td>
            <td>
                <a href="{% url 'tasks:tag-update' tag.pk %}" class="btn btn-primary btn-sm">Update</a>
            </td>
            <td>
                <a href="{% url 'tasks:tag-delete' tag.pk %}" class="btn btn-danger btn-sm">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task</h1>
  <p>Are you sure?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'tasks:home' %}" class="btn btn-secondary">No</a>

  </form>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h2>{{ object|yesno:"Update,Create" }} task</h2>
 <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Add task" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}

{% block content %}
<h1>ToDo list <a href="{% url 'tasks:task-form' %}" class="btn btn-primary float-end">Add Task</a>
</h1>
    {% for task in tasks %}

  <div class="card mb-3 p-3">
      <h3>{{ task.content }}</h3>

        <form action="{% url 'tasks:task-toggle' task.pk %}" method="post" style="display:inline;">
            {% csrf_token %}
            {% if task.is_done %}
                <button type="submit" class="btn btn-secondary btn-sm float-end">Undo</button>
            {% else %}
                <button type="submit" class="btn btn-success btn-sm float-end">Complete</button>
            {% endif %}
        </form>

      <p>{{ task.created_datetime }}
          {% if task.deadline %}
            <span class="text-danger">Deadline: {{ task.deadline }}</span>
          {% endif %}
      </p>

      <p>
        {% if task.tags.all %}
            {% for tag in task.tags.all %}
                Tags: {{ tag.name }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        {% endif %}
      </p>

    <div class="float-end">
      <a href="{% url 'tasks:task-update' task.pk %}" class="btn btn-primary btn-sm">Update</a>
      <a href="{% url 'tasks:task-delete' task.pk %}" class="btn btn-danger btn-sm">Delete</a>
    </div>

  </div>
{% endfor %}
{% endblock %}